import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/layout/footer/page";
import ScrollToTopButton from "@/layout/scroll/page";
import SocialMediaIcons from "@/layout/socail/page";


// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Paragon Group",
  description: "Generated by create next app",
  icons: {
    icon: "/plogoTop.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* <header>
            <Header />
          </header> */}

          <main>
            <div>{children}</div>
          </main>

          <footer>
            <Footer />
          </footer>

          {/* Scroll-to-Top Button component */}
          <ScrollToTopButton/>
          <SocialMediaIcons/>
        </div>
      </body>
    </html>
  );
}
