import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/layout/footer/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Paragon Group",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Paragon Group",
  description: "Generated by create next app",
  icons: {
    icon: "/plogoTop.jpg", // Or use /favicon.png if you're using PNG format
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          {/* <header>
            <Header />
          </header> */}

          <main>
            <div>{children}</div>
          </main>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
